"""Model management: registry, local cache and downloads.
Split out of a single 845-line module. Everything the rest of the app
imported from livetranslate.model_manager is re-exported here, so no call
site changed."""

from livetranslate.model_manager.registry import (  # noqa: F401
    ASR_DISPLAY_NAMES,
    ASR_MODEL_IDS,
    ASR_MODEL_IDS_HF,
    DEFAULT_FUNASR_MODEL,
    FUNASR_LEGACY_ENGINE_ALIASES,
    FUNASR_MODEL_PROFILES,
    SENSEVOICE_ONNX_FILES,
    _CACHE_MODELS,
    _MODEL_SIZE_BYTES,
    _WHISPER_SIZES,
    asr_model_id,
    funasr_display_name,
    funasr_model_id,
    funasr_model_options,
    funasr_profile,
    funasr_supports_padding,
    migrate_funasr_settings,
    normalize_asr_engine_selection,
    normalize_funasr_model_key,
)
from livetranslate.model_manager.cache import (  # noqa: F401
    APP_DIR,
    MODELS_DIR,
    _HF_TOKEN_FROM_SETTINGS,
    _custom_whisper_path,
    _has_silero_pkg,
    _hf_repo_complete,
    _hf_snapshot_name,
    _is_builtin_whisper_cache,
    _ms_model_path,
    apply_cache_env,
    apply_hf_token,
    dir_size,
    format_size,
    get_cache_entries,
    get_local_model_path,
    get_missing_models,
    is_asr_cached,
    is_faster_whisper_model_dir,
    is_silero_cached,
    list_local_faster_whisper_models,
    local_faster_whisper_display_name,
    qwen_weights_present,
    resolve_custom_whisper_model,
    sensevoice_onnx_paths,
)
from livetranslate.model_manager.download import (  # noqa: F401
    _PROXY_ENV_KEYS,
    _load_silero_relaxed_ssl,
    _proxy_env,
    download_asr,
    download_silero,
    ensure_qwen_weights,
    neutralize_funasr_requirements,
)

__all__ = [
    "ASR_DISPLAY_NAMES",
    "ASR_MODEL_IDS",
    "ASR_MODEL_IDS_HF",
    "DEFAULT_FUNASR_MODEL",
    "FUNASR_LEGACY_ENGINE_ALIASES",
    "FUNASR_MODEL_PROFILES",
    "SENSEVOICE_ONNX_FILES",
    "asr_model_id",
    "funasr_display_name",
    "funasr_model_id",
    "funasr_model_options",
    "funasr_profile",
    "funasr_supports_padding",
    "migrate_funasr_settings",
    "normalize_asr_engine_selection",
    "normalize_funasr_model_key",
    "APP_DIR",
    "MODELS_DIR",
    "apply_cache_env",
    "apply_hf_token",
    "dir_size",
    "format_size",
    "get_cache_entries",
    "get_local_model_path",
    "get_missing_models",
    "is_asr_cached",
    "is_faster_whisper_model_dir",
    "is_silero_cached",
    "list_local_faster_whisper_models",
    "local_faster_whisper_display_name",
    "qwen_weights_present",
    "resolve_custom_whisper_model",
    "sensevoice_onnx_paths",
    "download_asr",
    "download_silero",
    "ensure_qwen_weights",
    "neutralize_funasr_requirements",
]
